﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace FileManagerLastTry
{
    public partial class MLModel
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"Totaltime", @"Totaltime"),new InputOutputColumnPair(@"Pages", @"Pages"),new InputOutputColumnPair(@"Words", @"Words"),new InputOutputColumnPair(@"Characters", @"Characters"),new InputOutputColumnPair(@"Lines", @"Lines"),new InputOutputColumnPair(@"Paragraphs", @"Paragraphs")})      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"Totaltime",@"Pages",@"Words",@"Characters",@"Lines",@"Paragraphs"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(@"Status", @"Status"))      
                                    .Append(mlContext.MulticlassClassification.Trainers.OneVersusAll(binaryEstimator:mlContext.BinaryClassification.Trainers.FastTree(new FastTreeBinaryTrainer.Options(){NumberOfLeaves=5,MinimumExampleCountPerLeaf=6,NumberOfTrees=5,MaximumBinCountPerFeature=708,LearningRate=0.253575394381546F,FeatureFraction=1F,LabelColumnName=@"Status",FeatureColumnName=@"Features"}), labelColumnName: @"Status"))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(@"PredictedLabel", @"PredictedLabel"));

            return pipeline;
        }
    }
}
